sudo: required

language: python

services:
  - docker

before_install:
 - docker pull condaforge/linux-anvil

script:

 - echo "Travis build directory is ${TRAVIS_BUILD_DIR}"
 - docker run -e TRAVIS_PYTHON_VERSION
              -e TRAVIS_BRANCH
              -e CONDA_UPLOAD_TOKEN
              -e TRAVIS_OS_NAME
              -e TRAVIS_BUILD_NUMBER
              -e TRAVIS_BUILD_DIR
              -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}
              -it --rm -e user_id=`id -u`
              condaforge/linux-anvil
              /bin/bash -c "source ${TRAVIS_BUILD_DIR}/ci/build_and_test.sh"

env:
  matrix:
    secure: ht6GWpJyaTqTCQzTXuf7IQDKyl1OUISFXzHaLCcurBY5lZVkK+NIGaVMw0wNksQbgpF5t7JyojK39+usJ1WeYD4xvi3n7KxU9Cy8MGAuyY8iWFCmnVtkBoDkghGQBuUzf2UZ24IcH1JtlgOx28qJhEdXLfWPDd9/OvJLMrkpwcKcn0XV3dcheYvs3EyV8kyxfbaV3G9DsHY1bFZjGRzOATBuwCSpjkV5WxBq0dpDoilx6JY9uMydKU81PtxHbCQmP/8ZaT9eemw1qhBfrqbhU+CbwG0PDt7lG8SkXAIOQRJo/aJ7DvxtOQAvjuM1CUsKa8yTnyDHvxHVIcLZmiuWi/Cat20/v89iyBgXguDbKAGwg4gIW/QSfxS9IFR3eR5EX8NuTZ9tcAHoa+AHou5Km/iDoEjlqu11CFr/QYtaqFcnkMpuVs4mYfdiU5xLtZryiBqec0HO8xD9Q4IKIbEGMyulJ3NBwqQ6x9iHtqJrM0JinAynLXTcHHGzOhD+YVZbT4EzlH+8dLuMj33DYdJATZAt7pIpxskqBXvPm+qKPs5TUtxDtOinpuBk264kQdxUFXFpAzL5x2qguTauhi+t4f/bMVsFcq3KsL3nn3J021ysEzZqeGmmGs6hHfGTZbZNgMhtyO+18WHtnDOD5s8fjO+58T/Z0hqJbrfjulsNNr8=
