sudo: required

language: python

services:
  - docker

before_install:
 - docker pull giacomov/xspec-docker
 - docker ps -a
 - ls $TRAVIS_BUILD_DIR


script:
 - docker run --rm -it -e user_id=`id -u` -v $TRAVIS_BUILD_DIR:/travis_build_dir giacomov/xspec-docker /bin/bash -c "source /travis_build_dir/test_inside_docker.sh"

after_success:
 - codecov
