{% set name = "astromodels" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#  git_url: https://github.com/threeml/{{ name }}.git
  path: ../../

requirements:
  build:
    - {{ compiler('c') }} # [linux]
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('fortran') }} # [linux]
    - xspec-modelsonly
    - cfitsio
    #- cfitsio
    - cfitsio==3.470
    - ccfits
    - wcslib==5.20
    #- wcslib
    - wcslib
    - krb5==1.14.6 # [py2k]
    - readline==6.2 # [py2k]

  host:
    - python
    - setuptools
    - pip
    - numpy
    - pyyaml
    #- astropy
    #- scipy
    - numdifftools
    #- hdf5
    #- pytables
    - pandas>=0.23
    #- cfitsio
    - cfitsio==3.470
    - ccfits
    - wcslib==5.20
    #- wcslib
    - wcslib
    - xspec-modelsonly
    - future
    - krb5==1.14.6 # [py2k]
    - readline==6.2 # [py2k]
    - h5py

  run:
    - python
  #  - libgfortran
    - numpy
    - pyyaml
    - astropy
    #- scipy
    - numdifftools
    #- hdf5
    - pytables
    - pandas>=0.23
    - dill
    #- cfitsio
    - cfitsio==3.470
    - ccfits
    - wcslib==5.20
    #- wcslib
    - future
    - krb5==1.14.6 # [py2k]
    - readline==6.2 # [py2k]
    - h5py

build:
  script: python -m pip install --verbose --no-deps --ignore-installed .
  skip: true  # [win]
#  skip: true  # [py3k]

#test:
#  # Python imports
#  imports:
#    - astromodels
#    - astromodels.core
#    - astromodels.functions
#    - astromodels.functions.dark_matter
#    - astromodels.sources
#    - astromodels.utils
#    - astromodels.xspec

#  commands:
#    - pytest -vv --pyargs {{ name }}

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

#  requires:
#    - xspec-modelsonly


about:
  home: https://github.com/threeml/astromodels
  license: UNKNOWN
  summary: 'Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
