{% set name = "astromodels" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
#  git_url: https://github.com/giacomov/{{ name }}.git
  path: ../../

requirements:
  build:
    - toolchain
    - python
    - gcc  # [linux]
    - libgfortran
    - setuptools
    - pip
    - numpy
    - pyyaml
    - astropy
    - scipy
    - numdifftools
    - hdf5
    - pytables
    - pandas
    - xspec-modelsonly

  run:
    - python
    - dill
    - numpy
    - pyyaml
    - astropy
    - scipy
    - numdifftools
    - hdf5
    - pytables
    - pandas
    - libgcc  # [linux]
    - libgfortran

build:
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]
  skip: true  # [py3k]

test:
  # Python imports
  imports:
    - astromodels
    - astromodels.core
    - astromodels.functions
    - astromodels.functions.dark_matter
    - astromodels.sources
    - astromodels.utils
    - astromodels.xspec

#  commands:
#    - pytest -vv --pyargs {{ name }}

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - xspec-modelsonly


about:
  home: https://github.com/giacomov/astromodels
  license: UNKNOWN
  summary: 'Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
