name: test_env

channels:
  - conda-forge
  - xspecmodels
  - defaults
  
dependencies:
  - python
  - mkl
  - numpy
  - pyyaml>=5.1
  - astropy
  - scipy
  - numdifftools
  - hdf5
  - pytables
  - pandas>=0.23
  - dill
  - cfitsio==4.1.0
  - ccfits
  - wcslib=7.7
  - future
  - xspec-modelsonly==6.30.1
  - numba
  - h5py<3.2
  - interpolation>=2.1.5
  - libgfortran
  - colorama
  - rich
